### ISSUE TITLE
Automate converting older ontology terms to newer in datasets

### ISSUE THREAD

**Issue by nayib-jose-gloria** [chanzuckerberg/single-cell#346]
Per Jason's review of the data corpus and the updated ontology changes going into schema 3.0.0, the following maps the 2.0.0 dataset ontology term -> 3.0.0 ontology term that the convert cli command should automatically change to. 

EFO:0030002 (BD Rhapsody): EFO:0700003
EFO:0010183 (BD Rhapsody): EFO:0700003
MONDO:0008345: MONDO:0800029
MONDO:0004553: MONDO:0017853
CL:0002609: CL:0010012
CL:0011107: CL:0000636

**Comment by jychien** [comment]
Hello Nayib. wanted to confirm that the cli can convert both anndata=0.7 or anndata=0.8 h5ad files to correctly formatted anndata=0.8 files?

I put both `EFO:0030002 (BD Rhapsody)` and `EFO:0010183 (BD Rhapsody)`, and the h5ad can be found on [google drive](https://drive.google.com/file/d/1QeTSmXyhlbq8YWszlpgbXuDGfaaNzJJs/view?usp=sharing). For reference, the original dataset was the h5ad downloaded from [this collection](https://cellxgene.cziscience.com/collections/2902f08c-f83c-470e-a541-e463e25e5058). I ran the convert option, and got the ValueError below.  I've ran the converter for the MONDO terms listed above, and it ran correctly, so I am thinking it might be specific to the assay_ontology_term_id.

> % cellxgene-schema convert ~/Downloads/adult_ovary_ontologies.h5ad ~/Downloads/adult_ovary_ontologies_converted.h5ad
Converting /Users/jychien/Downloads/adult_ovary_ontologies.h5ad into /Users/jychien/Downloads/adult_ovary_ontologies_converted.h5ad
column 'suspension_type' not found in obs. Adding column and auto-assigning value where possible.
Dataset contains row(s) with assay_ontology_term_id EFO:0010183 (BD Rhapsody). These cannot be auto-assigned a suspension type, please assign a suspension_type manually and validate.
Dataset contains row(s) with assay_ontology_term_id EFO:0030002 (BD Rhapsody). These cannot be auto-assigned a suspension type, please assign a suspension_type manually and validate.
Traceback (most recent call last):
  File "/Users/jychien/miniconda3/envs/validate_pypi/bin/cellxgene-schema", line 8, in <module>
    sys.exit(schema_cli())
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/cellxgene_schema/cli.py", line 96, in convert
    convert(input_file, output_file)
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/cellxgene_schema/convert.py", line 152, in convert
    update_categorical_column_vals(
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/cellxgene_schema/convert.py", line 142, in update_categorical_column_vals
    dataframe[column_name] = dataframe[column_name].cat.rename_categories(
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/pandas/core/accessor.py", line 94, in f
    return self._delegate_method(name, *args, **kwargs)
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/pandas/core/arrays/categorical.py", line 2747, in _delegate_method
    res = method(*args, **kwargs)
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/pandas/core/arrays/categorical.py", line 1065, in rename_categories
    cat.categories = [new_categories.get(item, item) for item in cat.categories]
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/pandas/core/arrays/categorical.py", line 749, in categories
    new_dtype = CategoricalDtype(categories, ordered=self.ordered)
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py", line 183, in __init__
    self._finalize(categories, ordered, fastpath=False)
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py", line 337, in _finalize
    categories = self.validate_categories(categories, fastpath=fastpath)
  File "/Users/jychien/miniconda3/envs/validate_pypi/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py", line 534, in validate_categories
    raise ValueError("Categorical categories must be unique")
ValueError: Categorical categories must be unique

**Comment by nayib-jose-gloria** [comment]
Thanks for flagging--I've updated to fix this bug, you can install the latest rc by running:

`pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ cellxgene-schema==3.0.0rc2`

**Comment by jychien** [comment]
Everything looks good! I've rerun the cell_type, disease, and assay conversions, and they've all been converted appropriately. I've manually updated the suspension_type and they have passed validation. I've taken both AnnData=0.7 and AnnData=0.8 files. Thanks!
